### ISSUE TITLE
sbt-rewarn 0.1.2 crashes

### ISSUE THREAD

**Issue by sideeffffect** [rtimush/sbt-rewarn#22]
The version 0.1.2 crashes with
```
[info] compiling 2 Scala sources to /home/runner/work/sbt-decent-scala/sbt-decent-scala/target/scala-2.12/sbt-1.0/classes ...
[info] done compiling
Error:  scala.MatchError: sbt.rewarn.RewarnReporterProxy@6cce1f60 (of class sbt.rewarn.RewarnReporterProxy)
Error:  	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2146)
Error:  	at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2099)
Error:  	at sbt.internal.io.Retry$.apply(Retry.scala:40)
Error:  	at sbt.internal.io.Retry$.apply(Retry.scala:23)
Error:  	at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
Error:  	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2096)
Error:  	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
Error:  	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
Error:  	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
Error:  	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
Error:  	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
Error:  	at sbt.Execute.work(Execute.scala:291)
Error:  	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
Error:  	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
Error:  	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
Error:  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Error:  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
Error:  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Error:  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Error:  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Error:  	at java.base/java.lang.Thread.run(Thread.java:834)
Error:  (Compile / compileIncremental) scala.MatchError: sbt.rewarn.RewarnReporterProxy@6cce1f60 (of class sbt.rewarn.RewarnReporterProxy)
Error:  Total time: 9 s, completed Oct 20, 2020, 5:21:52 PM
Error: Process completed with exit code 1.
```

**Comment by rtimush** [comment]
Hi @sideeffffect, thanks for the report. Which sbt version do you use?

**Comment by sideeffffect** [comment]
1.4.1, I believe

**Comment by sideeffffect** [comment]
Scratch that, it was most likely the one before, so 1.4.0.
(I've just tried it on 1.4.1 and it works OK.)

**Comment by rtimush** [comment]
Ok, then I will close the issue — sbt-rewarn anyway didn't work in sbt 1.4.0 because of #15, and crashing is maybe even better than being silently broken.
